version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"     # opens PRs once a week
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "ci"
    rebase-strategy: "disabled"  # keep PR history readable

