# GitHub Funding configuration for Bits to Banking

# You can specify multiple options here. GitHub will show a "Sponsor" button.
# In this case, we direct users to our SUPPORT.md for donation details.

custom:
  - https://github.com/umicom-foundation/Bits2Banking/blob/main/SUPPORT.md
