# Canonical label set for Bits2Banking
- name: "chapter:submission"
  color: "0e8a16"
  description: "New chapter/section uploaded under raw_docs/<slug>/"

- name: "volume:proposal"
  color: "0366d6"
  description: "Proposal to start a new volume"

- name: "type:ingest"
  color: "5319e7"
  description: "Ingest/CI pipeline related"

- name: "type:docs"
  color: "0075ca"
  description: "Documentation and site"

- name: "type:content"
  color: "c2e0c6"
  description: "Book content updates"

- name: "type:build"
  color: "fbca04"
  description: "Build scripts / automation"

- name: "good first issue"
  color: "7057ff"
  description: "Friendly for first-time contributors"

- name: "help wanted"
  color: "008672"
  description: "Maintainer would appreciate help"

- name: "blocked"
  color: "d93f0b"
  description: "Needs input/decision before proceeding"

- name: "needs:review"
  color: "d876e3"
  description: "Awaiting maintainer review"

- name: "needs:changes"
  color: "b60205"
  description: "Requested changes before merge"

