# Automatically label PRs based on changed paths

"type:content":
  - "raw_docs/**"
  - "content/volumes/**"
  - "chapters/**"

"type:docs":
  - "docs/**"
  - "mkdocs.yml"
  - "*.md"
  - "**/*.md"

"type:ingest":
  - ".github/workflows/ingest.yml"

"type:build":
  - "scripts/**"
  - ".build.ps1"
  - "Makefile"
  - ".github/workflows/build-volume0.yml"
  - ".github/workflows/pages.yml"
  - ".github/workflows/lint.yml"

"needs:review":
  - ".github/**"

