# .typos.toml — repo-level config for crate-ci/typos

[default]
# Ignore generated/output areas (same spirit as your CI find patterns)
extend-ignore-re = [
  "volumes/.*",
  "book/.*",
  "site/.*",
  ".github/ISSUE_TEMPLATE/.*"
]

[default.extend-words]
# Project/tech nouns
Calypso   = "Calypso"
TMS       = "TMS"
Umicom    = "Umicom"
MkDocs    = "MkDocs"
DOCX      = "DOCX"
GitHub    = "GitHub"
RISC      = "RISC"
PnL       = "PnL"
Wise      = "Wise"

# Allow lowercase 'github' in code/links if you use it that way
"github"  = "github"

# Finance & Islamic finance terms we use a lot
SME        = "SME"
SMEs       = "SMEs"
Sukuk      = "Sukuk"
Hawala     = "Hawala"
Riba       = "Riba"
Shariah    = "Shariah"
Taqwa      = "Taqwa"
Mudarabah  = "Mudarabah"
Musharakah = "Musharakah"
Ijarah     = "Ijarah"
Sakk       = "Sakk"

# Arabic names / transliterations (prevent false positives like Abd/ʿAbd)
"Abd"       = "Abd"
"ʿAbd"      = "ʿAbd"
"al-Malik"  = "al-Malik"
Umayyad     = "Umayyad"
