[default]
extend-ignore-re = [
  "volumes/.*",
  "book/.*",
  "site/.*"
]

[default.extend-words]
Calypso = "Calypso"
TMS = "TMS"
Umicom = "Umicom"
MkDocs = "MkDocs"
Docx = "Docx"
Github = "GitHub"
RISC = "RISC"
PnL = "PnL"
github = "github"   # allow lowercase github