site_name: Bits to Banking
site_url: https://umicom-foundation.github.io/Bits2Banking
repo_url: https://github.com/umicom-foundation/Bits2Banking
repo_name: umicom-foundation/Bits2Banking

theme:
  name: material

# Keep this minimal so 'strict: true' passes. We only link the one page that exists in docs/.
nav:
  - Home: docs/index.md

strict: true
