site_name: "Bits2Banking"
site_description: "Open, practical education: from first principles to ethical finance"
site_author: "Umicom Foundation"
repo_url: "https://github.com/umicom-foundation/Bits2Banking"
repo_name: "umicom-foundation/Bits2Banking"
edit_uri: "edit/main/content/"

docs_dir: content
site_dir: site

theme:
  name: material
  language: en
  features:
    # Nice UX
    - navigation.instant           # fast page transitions
    - navigation.tabs              # top-level nav tabs
    - navigation.sections          # show section groupings
    - navigation.footer            # auto Previous/Next links
    - toc.integrate                # ToC in the right sidebar integrated
    - content.code.copy            # copy button on code blocks
    - content.action.edit          # "Edit this page" button

nav:
  - Quick Upload via raw_docs: CONTRIBUTING_RAW_DOCS.md
  - Home: index.md

  - "Volume 1 — Islam: Blueprint for Life":
      - "Introduction to Islam — A Complete Way of Life": v001_islam_blueprint_for_life/introduction_to_islam.md
      - "History of Money": v001_islam_blueprint_for_life/history_of_money.md
      - "Decline of Sound Money": v001_islam_blueprint_for_life/decline_of_sound_money.md
      - "Modern Banking and Finance": v001_islam_blueprint_for_life/modern_banking_and_finance.md
      - "Technology and Banking": v001_islam_blueprint_for_life/technology_and_banking.md
      - "Islamic Finance and the Future": v001_islam_blueprint_for_life/islamic_finance_and_future.md
      - "Umicom — Asset-Backed Stable Coin": v001_islam_blueprint_for_life/umicom_abs_coin.md
      - "Governance Firewalls": v001_islam_blueprint_for_life/governance_firewalls.md
      - "Hall of Shame — Collaboration and Betrayal": v001_islam_blueprint_for_life/hall_of_shame_collaboration_and_betrayal.md
      - "Recap": v001_islam_blueprint_for_life/recap.md

  - Volumes:
      - Index: VOLUMES.md

plugins:
  - search

markdown_extensions:
  # Structure & links
  - toc:
      permalink: true
  - tables
  - def_list
  - footnotes
  - admonition
  - attr_list
  - md_in_html

  # Pymdown extensions (already bundled with Material)
  - pymdownx.details          # collapsible details blocks
  - pymdownx.superfences      # fenced blocks inside other blocks
  - pymdownx.emoji            # emoji shortcodes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
