site_name: Bits to Banking (Open Book)
site_url: https://umicom-foundation.github.io/Bits2Banking/
repo_url: https://github.com/umicom-foundation/Bits2Banking
repo_name: umicom-foundation/Bits2Banking

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate

# Docs and site folders
docs_dir: chapters
site_dir: site

nav:
  - Home: index.md
  - Volume 1 — Islamic Foundations:
    - Chapter 1 — Introduction to Islam: volume1_islamic_foundations/chapter01_introduction_to_islam.md
    - Chapter 2 — The History of Money and Trade in Islam: volume1_islamic_foundations/chapter02_history_of_money.md
    - Chapter 3 — The Decline of Sound Money: volume1_islamic_foundations/chapter03_decline_of_sound_money.md
    - Chapter 4 — Modern Banking and Finance: volume1_islamic_foundations/chapter04_modern_banking_and_finance.md
    - Chapter 5 — Technology and Banking: volume1_islamic_foundations/chapter05_technology_and_banking.md
    - Chapter 6 — Islamic Finance Today and Tomorrow: volume1_islamic_foundations/chapter06_islamic_finance_and_future.md
    - Chapter 7 — Umicom Asset-Backed Security Coin (Concept): volume1_islamic_foundations/chapter07_umicom_abs_coin.md
    - Recap: volume1_islamic_foundations/chapter07_recap.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list

plugins:
  - search
