site_name: Bits to Banking — Open Book
site_url: https://umicom-foundation.github.io/Bits2Banking
repo_url: https://github.com/umicom-foundation/Bits2Banking
repo_name: umicom-foundation/Bits2Banking

# Source and output
docs_dir: content
site_dir: site

# Theme: keep default (no extra plugins/deps needed)
theme:
  name: mkdocs

# Navigation: list only what you want visible in the site nav
nav:
  - Home: index.md
  - Volume v001 — Islam: A Complete Blueprint for Life:
    - 0001 — Introduction to Islam: v001_islam_blueprint_for_life/0001_introduction_to_islam.md
    - 0002 — Corruption, Ideologies & Betrayal: v001_islam_blueprint_for_life/0002_corruption_ideologies_and_betrayal.md
    - 0003 — History of Money: v001_islam_blueprint_for_life/0003_history_of_money.md
    # Add more chapters here as you create 0004_*.md, 0005_*.md, etc.

# Strict build helps catch broken links/paths in CI
strict: true
