site_name: Bits to Banking
site_url: https://umicom-foundation.github.io/Bits2Banking
repo_url: https://github.com/umicom-foundation/Bits2Banking
repo_name: umicom-foundation/Bits2Banking

theme:
  name: material

nav:
  - Home: index.md

strict: true
