site_name: "Bits2Banking"
site_description: "Open curriculum: from computing basics to ethical finance"
site_url: "https://umicom-foundation.github.io/Bits2Banking/"
repo_url: "https://github.com/umicom-foundation/Bits2Banking"
repo_name: "umicom-foundation/Bits2Banking"

docs_dir: "content"
site_dir: "site"

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.footer   # shows Previous/Next buttons
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji

nav:
  - "Home": index.md
  - "v001 — Islam, Blueprint for Life":
      - "Introduction to Islam": v001_islam_blueprint_for_life/introduction_to_islam.md
      - "History of Money": v001_islam_blueprint_for_life/history_of_money.md
      - "Decline of Sound Money": v001_islam_blueprint_for_life/decline_of_sound_money.md
      - "Modern Banking and Finance": v001_islam_blueprint_for_life/modern_banking_and_finance.md
      - "Technology and Banking": v001_islam_blueprint_for_life/technology_and_banking.md
      - "Islamic Finance and the Future": v001_islam_blueprint_for_life/islamic_finance_and_future.md
      - "Umicom ABS Coin": v001_islam_blueprint_for_life/umicom_abs_coin.md
      - "Recap": v001_islam_blueprint_for_life/recap.md
