site_name: Bits to Banking
site_url: https://umicom-foundation.github.io/Bits2Banking
repo_url: https://github.com/umicom-foundation/Bits2Banking
repo_name: umicom-foundation/Bits2Banking

docs_dir: content
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Volume 1 — Islam: Blueprint for Life:
    - Introduction to Islam: v001_islam_blueprint_for_life/introduction_to_islam.md
    - History of Money: v001_islam_blueprint_for_life/history_of_money.md
    - Decline of Sound Money: v001_islam_blueprint_for_life/decline_of_sound_money.md
    - Modern Banking & Finance: v001_islam_blueprint_for_life/modern_banking_and_finance.md
    - Technology & Banking: v001_islam_blueprint_for_life/technology_and_banking.md
    - Islamic Finance & the Future: v001_islam_blueprint_for_life/islamic_finance_and_future.md
    - Governance Firewalls: v001_islam_blueprint_for_life/governance_firewalls.md
    - Hall of Shame — Collaboration & Betrayal: v001_islam_blueprint_for_life/hall_of_shame_collaboration_and_betrayal.md
    - Umicom ABS Coin (Asset-Backed): v001_islam_blueprint_for_life/umicom_abs_coin.md
    - Recap: v001_islam_blueprint_for_life/recap.md

plugins:
  - search

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

strict: true
