site_name: Bits to Banking
site_url: https://umicom-foundation.github.io/Bits2Banking
repo_url: https://github.com/umicom-foundation/Bits2Banking
repo_name: umicom-foundation/Bits2Banking

docs_dir: .          # <-- important so MkDocs can read chapters/ at repo root
theme:
  name: material

nav:
  - Home: README.md
  - Volume 1 — Islamic Foundations:
    - Chapter 1: chapters/volume1_islamic_foundations/chapter01_introduction_to_islam.md
    - Chapter 2: chapters/volume1_islamic_foundations/chapter02_history_of_money.md
    - Chapter 3: chapters/volume1_islamic_foundations/chapter03_decline_of_sound_money.md
    - Chapter 4: chapters/volume1_islamic_foundations/chapter04_modern_banking_and_finance.md
    - Chapter 5: chapters/volume1_islamic_foundations/chapter05_technology_and_banking.md
    - Chapter 6: chapters/volume1_islamic_foundations/chapter06_islamic_finance_and_future.md
    - Chapter 7: chapters/volume1_islamic_foundations/chapter07_umicom_abs_coin.md
    - Recap:     chapters/volume1_islamic_foundations/chapter07_recap.md

strict: true
