blank_issues_enabled: false
contact_links:
  - name: Quick Upload via raw_docs
    url: https://github.com/umicom-foundation/Bits2Banking/blob/main/docs/CONTRIBUTING_RAW_DOCS.md
    about: Upload .md/.docx/.pdf under raw_docs/<slug> and CI will ingest it into content/volumes/<slug>.

