Param(
  [Parameter(Mandatory = $true)]
  [string]$Slug
)

# --- Normalize slug first (lowercase, spaces/underscores -> hyphens, strip invalid) ---
$normalized = ($Slug -replace '[ _]+','-').ToLower() -replace '[^a-z0-9\-]',''
if ($normalized -ne $Slug) {
  Write-Host "Normalized slug: '$Slug' -> '$normalized'" -ForegroundColor Yellow
}
$Slug = $normalized

# Validate final slug
if ($Slug -notmatch '^[a-z0-9]+(-[a-z0-9]+)*$') {
  Write-Error "Invalid slug '$Slug'. Use lowercase-with-hyphens (e.g., introduction-to-islam)."
  exit 1
}

# --- Ensure we're at the repo root (simplest check) ---
if (-not (Test-Path ".git")) {
  Write-Host "Please run from the repository root (folder containing .git)" -ForegroundColor Yellow
  exit 1
}

# --- Target paths ---
$rawDir = Join-Path -Path "raw_docs" -ChildPath $Slug
$dstDir = Join-Path -Path "content\volumes" -ChildPath $Slug
$imgDir = Join-Path -Path $dstDir -ChildPath "images"

# --- Create folders (ok if they already exist) ---
New-Item -ItemType Directory -Force -Path $rawDir  | Out-Null
New-Item -ItemType Directory -Force -Path $dstDir  | Out-Null
New-Item -ItemType Directory -Force -Path $imgDir  | Out-Null

# Track images/ even if empty (optional; avoids "missing folder" confusion)
$gitkeep = Join-Path -Path $imgDir -ChildPath ".gitkeep"
if (-not (Test-Path $gitkeep)) {
  "" | Set-Content -Encoding Ascii $gitkeep
}

# --- Seed a small README inside raw_docs/<slug>/ (only if missing) ---
$rawReadme = Join-Path -Path $rawDir -ChildPath "README.md"
if (-not (Test-Path $rawReadme)) {
  @"
# Upload into `raw_docs/$Slug/`

Accepted: **.md**, **.docx**, **.pdf**  
Optional cover: **bookcover_<Title>.png** (or .jpg)

When you push to **main**:
1) \`.md\` is copied into \`content/volumes/$Slug/\`
2) \`.docx\` and text-based \`.pdf\` are converted to Markdown
3) New files are auto-numbered (\`ch01-…\`) and normalized (front matter, title, code fences)
4) \`bookcover_*\` becomes \`content/volumes/$Slug/images/cover.png\`

**Tips**
- Use lowercase-hyphenated filenames (no spaces)
- Keep size under: MD ≤ 2MB, DOCX ≤ 20MB, PDF ≤ 40MB, images ≤ 10MB
"@ | Set-Content -Encoding UTF8 $rawReadme
}

# --- Add placeholder chapter in content if none exist yet (keeps volume visible) ---
$placeholder = Join-Path -Path $dstDir -ChildPath "ch00-$Slug.md"
if (-not (Test-Path $placeholder)) {
  @"
---
title: "$Slug — placeholder"
volume: "$Slug"
status: draft
source: "scaffold"
created: $(Get-Date -Format 'yyyy-MM-dd')
updated: $(Get-Date -Format 'yyyy-MM-dd')
tags: []
---

# $Slug (placeholder)

This file was created by \`tools/new-volume.ps1\`.

Put your chapters in **raw_docs/$Slug/** as \`.md\`, \`.docx\`, or \`.pdf\`.  
The ingest workflow will mirror/convert them into this folder and auto-number new chapters.
"@ | Set-Content -Encoding UTF8 $placeholder
}

Write-Host ""
Write-Host "Scaffolded:" -ForegroundColor Green
Write-Host "  $rawDir" -ForegroundColor Green
Write-Host "  $dstDir" -ForegroundColor Green
Write-Host "  $imgDir" -ForegroundColor Green
Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  - Upload files to raw_docs/$Slug/" -ForegroundColor Cyan
Write-Host "  - git add . ; git commit -m 'scaffold: $Slug' ; git push" -ForegroundColor Cyan
