name: Ingest (detector)

on:
  push:
    paths:
      - "raw_docs/**"
      
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: List files changed under raw_docs in this push
        run: |
          echo "Changed files under raw_docs in this push:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^raw_docs/' || echo "None"
      - name: Guidance
        run: |
          echo "::notice title=Ingest Detected::Files were pushed to raw_docs/. In the next step, we'll add conversion (DOCX/PDF → Markdown) and open a structured PR into content/."
      - name: No changes detected
        if: ${{ github.event.before == github.sha }}
        run: echo "No changes detected under raw_docs/. Exiting."
      - name: Changes detected
        if: ${{ github.event.before != github.sha }}
        run: echo "Changes detected under raw_docs/. Proceeding to next steps."
      - name: Next Steps
        if: ${{ github.event.before != github.sha }}
        run: |
          echo "Next steps would include converting files from raw_docs/ to Markdown and creating a PR
          into the content/ directory. This part is not yet implemented." 
          echo "Please implement the conversion and PR creation logic here."
      - name: Final Notice
        if: ${{ github.event.before != github.sha }}
        run: |
          echo "::notice title=Ingest Process Complete::The ingest process has detected changes and is ready for the next steps. Please implement the conversion and PR creation logic."      
      - name: No changes final notice
        if: ${{ github.event.before == github.sha }}
        run: |
          echo "::notice title=No Changes Detected::No changes were detected under raw_docs/.
          The workflow has exited without further action."
      - name: End of Workflow
        run: echo "End of the ingest detection workflow." 
      - name: Passthrough .md files from raw_docs to content/volumes
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ github.event.before }}"
          HEAD="${{ github.sha }}"

          # List changed Markdown files under raw_docs/
          CHANGED=$(git diff --name-only "$BASE" "$HEAD" -- 'raw_docs/**/*.md' 'raw_docs/*.md' | tr -d '\r')
          if [ -z "$CHANGED" ]; then
            echo "No Markdown files changed under raw_docs/. Nothing to do."
            exit 0
          fi

          echo "Markdown files to ingest:"
          echo "$CHANGED"

          # Copy each file into content/volumes/<volume>/
          for f in $CHANGED; do
            # volume is the first folder after raw_docs/
            rel="${f#raw_docs/}"
            vol="${rel%%/*}"
            file="${f##*/}"

            # if file is directly in raw_docs/ (no subfolder), default to 'misc'
            if [ "$vol" = "$rel" ]; then vol="misc"; fi

            outdir="content/volumes/$vol"
            mkdir -p "$outdir"
            cp -f "$f" "$outdir/$file"
            echo "Copied $f -> $outdir/$file"
          done

          # Commit and push the mirrored files
          git config user.name  "umicom-bot"
          git config user.email "actions@users.noreply.github.com"
          git add content/volumes
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "ingest: copy Markdown from raw_docs to content/volumes"
          git push
  



