name: Ingest (raw_docs → content)

on:
  push:
    paths:
      - "raw_docs/**"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Work out a safe diff range (handles first-push edge cases)
      - name: Determine diff range
        id: diff
        shell: bash
        run: |
          BEFORE="${{ github.event.before }}"
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            BEFORE=$(git rev-parse HEAD~1 2>/dev/null || echo "")
          fi
          echo "before=$BEFORE" >> "$GITHUB_OUTPUT"
          echo "sha=${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Show changed files under raw_docs
        shell: bash
        run: |
          git diff --name-only "${{ steps.diff.outputs.before }}" "${{ steps.diff.outputs.sha }}" | grep '^raw_docs/' || echo "None"

      # --- Markdown passthrough (no conversion) ---
      - name: Passthrough Markdown files (.md)
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ steps.diff.outputs.before }}"
          HEAD="${{ steps.diff.outputs.sha }}"
          CHANGED=$(git diff --name-only "$BASE" "$HEAD" -- 'raw_docs/**/*.md' 'raw_docs/*.md' | tr -d '\r' || true)
          if [ -z "$CHANGED" ]; then
            echo "No .md files changed."
            exit 0
          fi
          for f in $CHANGED; do
            rel="${f#raw_docs/}"
            vol="${rel%%/*}"
            [ "$vol" = "$rel" ] && vol="misc"
            outdir="content/volumes/$vol"
            mkdir -p "$outdir"
            cp -f "$f" "$outdir/$(basename "$f")"
            echo "Copied $f -> $outdir/$(basename "$f")"
          done

      # --- DOCX → Markdown conversion (with images extraction) ---
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert DOCX to Markdown
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ steps.diff.outputs.before }}"
          HEAD="${{ steps.diff.outputs.sha }}"
          CHANGED=$(git diff --name-only "$BASE" "$HEAD" -- 'raw_docs/**/*.docx' 'raw_docs/*.docx' | tr -d '\r' || true)
          if [ -z "$CHANGED" ]; then
            echo "No .docx files changed."
            exit 0
          fi
          for f in $CHANGED; do
            rel="${f#raw_docs/}"
            vol="${rel%%/*}"
            [ "$vol" = "$rel" ] && vol="misc"
            base="$(basename "$f" .docx)"
            outdir="content/volumes/$vol"
            mkdir -p "$outdir/images/$base"
            pandoc "$f" \
              --extract-media="$outdir/images/$base" \
              -t gfm --wrap=none \
              -o "$outdir/${base}.md"
            echo "Converted $f -> $outdir/${base}.md"
          done

      # --- Commit & push any ingested files ---
      - name: Commit and push ingested files
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content/volumes || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "ingest: import from raw_docs (md passthrough + docx conversion)"
          git push
