name: Sync Labels

on:
  push:
    paths:
      - ".github/labels.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply labels from .github/labels.yml
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          # If you do NOT want the action to delete labels not in labels.yml, set skip-delete: true
          skip-delete: false
            # If you want to limit the action to only add labels (not delete or rename), set add-only: true
