name: Lint & Spell Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
         globs: |
            **/*.md
            !volumes/**
            !book/**
            !site/**
            !.github/ISSUE_TEMPLATE/**
            !.github/PULL_REQUEST_TEMPLATE.md


  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Use the stable major tag to avoid pinning a non-existent version
      - name: Typos (spell check)
        uses: crate-ci/typos@v1
